-- No-op placeholder for migration 20260519235014_publish_requires_dintero_onboarding.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
