-- No-op placeholder for migration 20260519003222_teams_cascade_on_seller_delete.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
