-- No-op placeholder for migration 20260512172453_drop_seller_address_fields.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
