-- No-op placeholder for migration 20260518112506_drop_course_level.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
