-- No-op placeholder for migration 20260513120600_drop_practical_info_from_courses.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
