-- No-op placeholder for migration 20260518000713_create_signup_serialize_on_txn.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
