-- No-op placeholder for migration 20260521220226_package_tier_allow_last_session.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
