-- No-op placeholder for migration 20260517235513_signups_confirmation_sent_at.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
