-- No-op placeholder for migration 20260511165322_course_format_and_delivery_mode.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
