-- No-op placeholder for migration 20260517235640_send_pending_confirmations_cron.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
