-- No-op placeholder for migration 20260418010000_security_and_rls_hardening.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
