-- No-op placeholder for migration 20260519122802_m1_final_drop_changed_by_and_unused_index.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
