-- No-op placeholder for migration 20260429095812_team_affiliations_and_course_listings.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
