-- No-op placeholder for migration 20260512154236_drop_profiles_avatar_url.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
