-- No-op placeholder for migration 20260529233713_course_lifecycle_reconciliation.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
