-- No-op placeholder for migration 20260425152302_simplify_spaces_invite_code_model.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
