-- No-op placeholder for migration 20260519112709_audit_step4_merge_permissive_selects.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
