-- No-op placeholder for migration 20260328010000_add_onboarding_tracking.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
