-- No-op placeholder for migration 20260520003824_package_proration_min_two_weeks.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
