-- No-op placeholder for migration 20260517192703_fix_notifications_dedupe_per_recipient.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
