-- No-op placeholder for migration 20260426185513_fix_create_course_idempotent_drop_legacy_params.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
