-- No-op placeholder for migration 20260423174117_fix_payment_audit_log_remove_stripe_refs.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
