-- No-op placeholder for migration 20260420135536_tighten_signups_insert_rls.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
