-- No-op placeholder for migration 20260519112604_audit_step2_fix_is_team_admin.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
