-- No-op placeholder for migration 20260417010000_drop_link_guest_bookings.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
