-- No-op placeholder for migration 20260512154029_add_seller_logos_bucket.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
