-- No-op placeholder for migration 20260519125831_harden_storage_helper_identity.
-- The pre-baseline SQL is archived in supabase/migrations_archive/20260601_prebaseline/.
-- Production already has this migration recorded in supabase_migrations.schema_migrations.
